### ISSUE TITLE
problem with download in buildroot

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-PHAL#10]
When I rebuild the image with build root I get this message. I checked the file and yes, I get the c3... sum.

```
ERROR: python-ovos-phal-0c7257f240ba9139b778c0670cf6a983b6aa18bd.tar.gz has wrong sha256 hash:
ERROR: expected: 6ae8287a8761b791d951346105abaea10e27e19504f366fafa92d29db343722c
ERROR: got     : c3dc69ce1a25a30eca6d49ee93a45799a50b570ac3c5770cd7a4a95575870c95
ERROR: Incomplete download, or man-in-the-middle (MITM) attack
```

**Comment by NeonDaniel** [comment]
@j1nx Any ideas here?

**Comment by j1nx** [comment]
Probably an mistake on my side. Double check the sha256 of the downloaded tar.gz and if indeed it is c3dc69ce1a25a30eca6d49ee93a45799a50b570ac3c5770cd7a4a95575870c95 you can safely change the sha256 wihin the .hash file within the python-ovos-phal directory

**Comment by denics** [comment]
@j1nx are you going to take care of it or do you want me to do a PR?

**Comment by j1nx** [comment]
@denics I assume this is fixed in one of the latest images by;

https://github.com/OpenVoiceOS/ovos-buildroot/commit/0d5efc85696b1bed5f9fd222c02034c42bfe1f6e

So if you would just to fix your current build run, you can do it yourself, otherwise pull in the latest code and it should be fixed. If not, please let me know as I might have screwed up completely.
